/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person1.glb --transform 
Files: person1.glb [18.84MB] > D:\Users\Ankit.Kumar\Documents\GitHub\wawatmos\react_three_fiber\public\person1-transformed.glb [670.11KB] (96%)
Author: image3dstudio (https://sketchfab.com/image3dstudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/person-eefb1c0d73864774b5fca1b00f510a4f
Title: person
*/

import { useGLTF } from '@react-three/drei'

export function Person1Model(props) {
  const { nodes, materials } = useGLTF('/models/person1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/person1-transformed.glb')
