/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person2.glb --transform 
Files: person2.glb [11.14MB] > D:\Users\Ankit.Kumar\Documents\GitHub\wawatmos\react_three_fiber\public\person2-transformed.glb [571.07KB] (95%)
Author: otaru (https://sketchfab.com/otaru)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/person-1b7eda8e39fd4567ba1c9a840fdcf4fb
Title: Person
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/person2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/person2-transformed.glb')
