/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person3.glb --transform 
Files: person3.glb [11.44MB] > D:\Users\Ankit.Kumar\Documents\GitHub\wawatmos\react_three_fiber\public\person3-transformed.glb [553.01KB] (95%)
Author: ENOAVA (https://sketchfab.com/yaoxl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/person-4f3e7c32866d4d37a555db822c8f10b9
Title: Person
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/person3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/person3-transformed.glb')
