/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person.glb --transform 
Files: person.glb [17.03MB] > D:\Users\Ankit.Kumar\Documents\GitHub\wawatmos\react_three_fiber\public\person-transformed.glb [577.96KB] (97%)
Author: scanontherun (https://sketchfab.com/scanontherun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/person-bcd49ca3bcfb43739fd90a8dbfcf5319
Title: Person
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/person-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/person-transformed.glb')
